### ISSUE TITLE
Logit lens demo: "logit lens" logit are inconsistent with visualization output token

### ISSUE THREAD

**Issue by Hugi-R** [freedmand/interpogate#1]
Hi!
First, interpogate is a really cool tool, I was finally able to "see" the Llama architecture and understand it a bit better. And having everything run in a notebook make it really easy to use.

Trying to piece together the visualization and the "logit lens" at the end of the demo, I'm confused to see the output token from layer 21 be different from the output token from the model.
I tried 2 changes: a fix to the displayed prob
```patch
- print(f"  #{j + 1}: {tokenizer.decode(idx)} (prob: {softmax[i][j]})")
+ print(f"  #{j + 1}: {tokenizer.decode(idx)} (prob: {softmax[i][idx]})")
```
and using the norm layer before the lm_head
```patch
- logits = lm_head(output[0])[0]
+ norm = interp.node('model.norm')
+ logits = lm_head(norm(output[0]))[0]
```
Resulting in:
```
Layer 21:
  #1: fact (prob: 0.06396484375)
  #2: way (prob: 0.05615234375)
  #3: ability (prob: 0.031982421875)
  #4: possibility (prob: 0.01177978515625)
  #5: amount (prob: 0.01007080078125)
  #6: story (prob: 0.009765625)
```

Now the tokens from layer 21 match the ones from the visualization, and have the same prob. But still they're missing the space (or "_") in front of them. What am I missing?

**Comment by freedmand** [comment]
Hey, thanks for noticing and identifying a fix for that! As for the tokenizer, I'm using a decode method which may strip whitespace. Let me see if I can get it to show in the same way as the frontend and I'll push up a patch

**Comment by freedmand** [comment]
Fixed in latest commit https://github.com/freedmand/interpogate/commit/9dac00f9a34b8a064c8bf3f530f3deccf9f2c92b. Got the tokenizer to work the same as the frontend using `tokenizer.convert_ids_to_tokens`. Thanks again!
